[build]
  # 先执行npm install确保所有依赖（包括dev）被安装，然后再构建
  command = "npm install && npm run build"
  # publish目录由Netlify Next.js插件自动处理

[build.environment]
  NODE_ENV = "production"
  # 可以保留这个，如果本地开发需要模拟路径
  # DISABLE_BASE_PATH = "true" 

# 移除所有重定向，让Next.js插件处理 